# Generated by Django 4.2.2 on 2023-06-23 14:31

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.management import create_permissions


def create_groups(apps, schema_editor):
    # Create user groups
    groups = ["Manager", "Officer"]
    for name in groups:
        Group.objects.create(name=name)

    # Permissions have to be created before applying them
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    all_perms = Permission.objects.all()
    manager_perms = [i for i in all_perms if i.content_type.app_label == "task"]
    officer_perms = [
        i for i in manager_perms if i.codename in ["view_task", "change_task"]
    ]
    Group.objects.get(name="Manager").permissions.add(*manager_perms)
    Group.objects.get(name="Officer").permissions.add(*officer_perms)


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("task", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_groups)]
